---
deployment:
  tasks:
    - export DEPLOYPATH=/home/activepe/public_html/
    - export REPO=/home/activepe/repositories/Activepetz/
    - /bin/cp -R "$REPO/js" $DEPLOYPATH
    - /bin/cp -R "$REPO/css" $DEPLOYPATH
    - /bin/cp -R "$REPO/media" $DEPLOYPATH
    - /bin/cp "$REPO/*.html" $DEPLOYPATH
