---
deployment:
  tasks:
    - export DEPLOYPATH=/home/activepe/public_html/
    - export REPO=/home/activepe/repositories/Activepetz/
    - /bin/cp -R "$REPO/js" $DEPLOYPATH
    - /bin/cp -R "$REPO/css" $DEPLOYPATH
    - /bin/cp -R "$REPO/media" $DEPLOYPATH
    - /bin/cp "$REPO/index.html" $DEPLOYPATH
    - /bin/cp "$REPO/contact_us.html" $DEPLOYPATH
    - /bin/cp "$REPO/rates.html" $DEPLOYPATH
    - /bin/cp "$REPO/services.html" $DEPLOYPATH
