name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - staging
      - containerised

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Git Short SHA
        id: gitsha
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/aj-owen/activepetz:${{ steps.gitsha.outputs.sha }} .

      - name: Retag 'latest'
        run: |
          docker tag ghcr.io/aj-owen/activepetz:${{ steps.gitsha.outputs.sha }} ghcr.io/aj-owen/activepetz:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/aj-owen/activepetz:${{ steps.gitsha.outputs.sha }} && \
          docker push ghcr.io/aj-owen/activepetz:latest


